import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const version = pkg.version;

// 1. Sync src/version.ts
const versionTsContent = `// Auto-generated by scripts/sync-version.mjs during build; do not edit manually.
export const VERSION = '${version}';
export const USER_AGENT = 'pi-jev-navigator/${version}';
`;
writeFileSync(resolve(root, 'src/version.ts'), versionTsContent, 'utf8');

// 2. Sync AGENTS.md
const agentsPath = resolve(root, 'AGENTS.md');
let agentsContent = readFileSync(agentsPath, 'utf8');
const titleRegex = /^# AGENTS\.md — pi-jev-navigator(?: v\S+)? Developer & Agent Guide/m;
if (titleRegex.test(agentsContent)) {
  agentsContent = agentsContent.replace(titleRegex, `# AGENTS.md — pi-jev-navigator v${version} Developer & Agent Guide`);
  writeFileSync(agentsPath, agentsContent, 'utf8');
} else {
  console.warn('Warning: Could not match title pattern in AGENTS.md');
}

console.log(`Synced version v${version} to src/version.ts and AGENTS.md`);
